# Use the latest LTS version of Node.js
FROM node:25-alpine
 
# Set the working directory inside the container
WORKDIR /app
 
# Copy package.json and package-lock.json
COPY package*.json ./
 
# Install dependencies
RUN npm install
 
# Copy the rest of your application files
COPY . .
 
# Expose the port your app runs on
EXPOSE 3000

# Enable polling for file changes
ENV CHOKIDAR_USEPOLLING=true
 
# Define the command to run your app
CMD ["npm", "start"]