import React, { useRef, useEffect } from 'react';

export default function TerminalOutput({ lines, theme, children }) {
  const bottomRef = useRef(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView?.({ behavior: 'smooth' });
  }, [lines]);

  return (
    <div className="terminal-output" role="log" aria-live="polite" aria-atomic="false" aria-label="Terminal output">
      {children}
      {lines.map((line) => (
        <div
          key={line.id}
          className={`terminal-line terminal-line--${line.type}`}
          style={{ color: getLineColor(line.type, theme) }}
        >
          {line.type === 'input' && (
            <span className="terminal-prompt" style={{ color: theme.prompt }}>
              ~/portfolio ${' '}
            </span>
          )}
          {line.type === 'input' ? (
            <span className="terminal-line-content">{line.content}</span>
          ) : (
            <span
              className="terminal-line-content"
              // Safe: all content is generated by our own command handlers
              // from static config data — never from raw user input
              dangerouslySetInnerHTML={{ __html: line.content }}
            />
          )}
        </div>
      ))}
      <div ref={bottomRef} />
    </div>
  );
}

function getLineColor(type, theme) {
  switch (type) {
    case 'error':
      return theme.error;
    case 'success':
      return theme.success;
    case 'system':
      return theme.accent;
    case 'input':
      return theme.foreground;
    default:
      return theme.foreground;
  }
}
